export const CLUB_AUDIT_ACTION = {
  COMMITTEE_PRICING_SAVED: "committee_pricing.saved",
  CLUB_WA_TEMPLATE_SAVED: "club_wa_template.saved",
  CLUB_WA_TEMPLATE_RESET: "club_wa_template.reset",
  CLUB_OPERATIONAL_SAVED: "club_operational.saved",
  CLUB_BRANDING_SAVED: "club_branding.saved",
  NOTIFICATION_PREFS_SAVED: "notification_preferences.saved",
  ADMIN_PROFILE_BOOTSTRAP_UPSERT: "admin_profile.bootstrap_upsert",
  ADMIN_INVITATION_CONSUMED: "admin_invitation.consumed",
  ADMIN_INVITATION_CREATED: "admin_invitation.created",
  ADMIN_INVITATION_REVOKED: "admin_invitation.revoked",
  ADMIN_PROFILE_CREATED_UI: "admin_profile.created_ui",
  ADMIN_PROFILE_ROLE_CHANGED: "admin_profile.role_changed",
  ADMIN_PROFILE_ACCESS_REVOKED: "admin_profile.access_revoked",
  ADMIN_PROFILE_MEMBER_LINK_CHANGED: "admin_profile.member_link_changed",
  ADMIN_PROFILE_DELETED_UI: "admin_profile.deleted_ui",
  EVENT_DELETED_UI: "event.deleted_ui",
  MASTER_MEMBER_DELETED_UI: "master_member.deleted_ui",
  BOARD_PERIOD_CREATED: "board_period.created",
  BOARD_PERIOD_UPDATED: "board_period.updated",
  BOARD_ROLE_CREATED: "board_role.created",
  BOARD_ROLE_UPDATED: "board_role.updated",
  BOARD_ROLE_DEACTIVATED: "board_role.deactivated",
  MANAGEMENT_MEMBER_CREATED: "management_member.created",
  MANAGEMENT_MEMBER_UPDATED: "management_member.updated",
  MANAGEMENT_MEMBER_PUBLIC_CODE_CHANGED: "management_member.public_code_changed",
  BOARD_ASSIGNMENT_CREATED: "board_assignment.created",
  BOARD_ASSIGNMENT_UPDATED: "board_assignment.updated",
  BOARD_ASSIGNMENT_REMOVED: "board_assignment.removed",
} as const;

export type ClubAuditAction =
  (typeof CLUB_AUDIT_ACTION)[keyof typeof CLUB_AUDIT_ACTION];
