/** Plain-text defaults before block editor (for migration tests). */
export const CLUB_EMAIL_LEGACY_PLAIN = {
  invoice: [
    'Halo {contact_name},',
    '',
    'Berikut tagihan pendaftaran Anda untuk {event_title} sebesar {total_amount_idr}.',
    '',
    'Mohon transfer ke:',
    'Bank: {bank_name}',
    'No. Rekening: {account_number}',
    'Atas nama: {account_name}',
    '',
    'Setelah transfer, unggah bukti pembayaran melalui panitia.',
  ].join('\n'),
  invoice_underpayment: [
    'Halo {contact_name},',
    '',
    'Terdapat kekurangan pembayaran untuk {event_title} sebesar {adjustment_amount_idr}.',
    '',
    'Mohon transfer ke:',
    'Bank: {bank_name}',
    'No. Rekening: {account_number}',
    'Atas nama: {account_name}',
    '',
    'Setelah transfer, unggah bukti pembayaran melalui panitia.',
  ].join('\n'),
  registration_approved: [
    'Halo {contact_name},',
    '',
    'Pembayaran Anda untuk {event_title} telah kami verifikasi. Pendaftaran Anda disetujui.',
    '',
    'Nomor pemesanan: {registration_id}',
    'Total terverifikasi: {computed_total_idr}',
    '',
    'Simpan email ini sebagai bukti pendaftaran.',
  ].join('\n'),
  magic_link: [
    'Klik tautan berikut untuk masuk ke halaman admin Match Screening:',
    '{magic_link_url}',
    '',
    'Link ini hanya berlaku sekali dan akan kedaluwarsa dalam 5 menit.',
    '',
    'Jika Anda tidak meminta link ini, abaikan email ini.',
  ].join('\n'),
} as const
